# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1ce80b986fd48ffe7c889b448d3faefdaf4477052d388d4b5327b29364e8eb2598fd3b0894dd72ddfbbb3e6f8421c2adc188c8cfb8f349525420e7b5ccb1bf9

test:
  secret_key_base: 6cd74723ffc2ce69e3cbd69571ee5f9e55f7267cdbf1e80fca0ceffbedded6e5df674804e6ac679c8bef7d6c6350cdd53f33adaff6f76234c4d2a5993c3b331f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
